### ISSUE TITLE
Clase duplicate

### ISSUE THREAD

**Issue by ionutab** [MihutBalasanu/sudoku#1]
Sa ne uitam putin la structura proiectului.
Ai clasele in 2 locuri.

Atat direct in folderul src observ ca ai 
**Main.java
MySudoku.java 
SudokuMove.java**
dar si in **src/sudoku** ai 
**Main.java
MySudoku.java
SudokuMove.java**

Vezi ca trebuie sa stergi si sa ramana doar cele corecte.

**Comment by MihutBalasanu** [comment]
Am sters.
