### ISSUE TITLE
Static scope

### ISSUE THREAD

**Issue by ionutab** [MihutBalasanu/sudoku#3]
https://github.com/MihutBalasanu/sudoku/blob/8c09db3ea174d9a4b0b8995ddd6a3da00fda5dc8/20181003_Sudoku/src/sudoku/MySudoku.java#L3

Daca clasa `MySudoku` reprezinta o instanta a unui joc de sudoku atunci vrei ca fiecare joc sa opereze doar pe starea lui interna.

Nici o metoda din clasa `MySudoku` nu trebuie sa aiba static scope.
Deci poti sa scoti cuvantul `static` din fata proprietatilor si metodelor.

Cand jucatorul incepe un joc nou trebuie sa instantiezi in `Main`
`MySudoku mySudoku = new MySudoku(<<dimensiune>>)`

**Comment by MihutBalasanu** [comment]
Ok
