### ISSUE TITLE
Split into 3 methods

### ISSUE THREAD

**Issue by ionutab** [MihutBalasanu/sudoku#4]
https://github.com/MihutBalasanu/sudoku/blob/8c09db3ea174d9a4b0b8995ddd6a3da00fda5dc8/20181003_Sudoku/src/sudoku/MySudoku.java#L41

Separa te rog in 3 metode:
```

isValidLine(SudokuMove sudokuMove)
isValidColumn(SudokuMove sudokuMove)
isValidRegion(SudokuMove sudokuMove)


```
in `isValidMove(SudokuMove sudokuMove)` le apelezi pe rand.

**Comment by MihutBalasanu** [comment]
Am facut-o si pe asta.
