### ISSUE TITLE
Unnecessary variables

### ISSUE THREAD

**Issue by ionutab** [MihutBalasanu/sudoku#5]
https://github.com/MihutBalasanu/sudoku/blob/8c09db3ea174d9a4b0b8995ddd6a3da00fda5dc8/20181003_Sudoku/src/sudoku/MySudoku.java#L52

Daca returnezi false in momentul in care ai determinat faptul ca mutarea este invalida nu mai are sens sa folosesti 
```

        boolean testLine = true;
        boolean testColumn = true;
        boolean testRegion = true;
```

**Comment by MihutBalasanu** [comment]
rezolvat
