### ISSUE TITLE
Move to separate class

### ISSUE THREAD

**Issue by ionutab** [MihutBalasanu/sudoku#6]
https://github.com/MihutBalasanu/sudoku/blob/8c09db3ea174d9a4b0b8995ddd6a3da00fda5dc8/20181003_Sudoku/src/sudoku/MySudoku.java#L28

Lasa asta cu smallSudoku deocamdata.
Eventual poti sa faci o clasa apoi cu `MySmallSudoku` dar sincer nu vad deocamdata rolul la treaba asta.

**Comment by MihutBalasanu** [comment]
M-am gandit in felul urmator: Fiecarui obiect sudokuMove ii corespunde o regiune unde trebuie testata mutarea. Daca elimin metoda imi pica metoda isValidRegion in forma actuala.

**Comment by ionutab** [comment]
Aaaaa.
Inteleg,
Deci, practic cu metoda asta `smallSudoku` extragi matricea de 3x3 cu zona in care a fost facuta mutarea.
Corect ?

Daca da, atunci e foarte bine.
Poti eventual sa-i dai o denumire mai clara, cum ar fi:
`extractSudokuRegionOfMove`

**Comment by MihutBalasanu** [comment]
Da, asta am intentionat.
Am redenumit.
